//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO_DET
    {
        public int ID_CARRITO { get; set; }
        public int NUM_LINEA { get; set; }
        public string COD_PRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal MONTO_SINIV { get; set; }
        public decimal DESCUENTO { get; set; }
        public decimal IMPUESTO { get; set; }
        public decimal TOTAL { get; set; }
    
        public virtual CARRITO_ENC CARRITO_ENC { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
